### ISSUE TITLE
can't trigger on edge on a waveform

### ISSUE THREAD

**Issue by thierry13790** [QuangHaiNguyen/Oscilloscope_STM32F746#2]
Hello, Thank you for your tool. I can't trigger on edge on a waveform ? How to do it ? did you qualified it ?

**Comment by QuangHaiNguyen** [comment]
hi @thierry13790 ,

you have to press the button trigger to activate the trigger function, then press the Marker button to activate the marker (to choose the voltage level of the triggering). You can press the Edge button to toggle between the rising edge and falling edge trigger

cheers,
Hai

**Comment by thierry13790** [comment]
Thank you ! I will check that and will let you know
