### ISSUE TITLE
bg.cpp file missing

### ISSUE THREAD

**Issue by GrantMTG** [QuangHaiNguyen/Oscilloscope_STM32F746#3]
I searched the repository but it does not appear to be there. It's part of the project though:

"no source": Error:  #5: cannot open source input file "..\..\Graphic\generated\images\src\bg.cpp": No such file or directory

**Comment by QuangHaiNguyen** [comment]
Hi @GrantMTG, this project was old so I dont remember what's going on but  I will have a look.

**Comment by GrantMTG** [comment]
HI. No worries, I think it builds OK anyway?

**Comment by QuangHaiNguyen** [comment]
@GrantMTG  Just check again, in Keil Project, you just need to remove the file bg.cpp from the project tree. That file does not contribute to the build. 

I dont have the board lying around to test the firmware, but it builds OK :D

**Comment by GrantMTG** [comment]
Thank you for this enjoyable project.

**Comment by QuangHaiNguyen** [comment]
Great!! then I will close the issue

**Comment by QuangHaiNguyen** [comment]
Issue closed
